version: '3'

interval: '500ms'

tasks:
    ts-build:
        internal: true
        sources:
            - ./src/**/*.ts
        cmds:
            - pnpm build-typescript

    dev:
        desc: Run dev mode on client
        env:
            NODE_ENV: development
        deps: [await-port]
        cmds:
            - pnpm dev

    build:
        deps: [ts-build]
        env:
            NODE_ENV: production

    install:
        cmds:
            - pnpm install

    await-port:
        internal: true
        cmds:
            - node ./scripts/await-port.js
