version: '3'

includes:
    client:
        taskfile: ./client
        dir: ./client
    interface:
        taskfile: ./interface
        dir: ./interface
    server:
        taskfile: ./server
        dir: ./server
    core:
        taskfile: ./core
        dir: ./core

tasks:
    build:
        desc: Build entire application
        cmds:
            - task: interface:build
            - task: client:build

    install:
        desc: Install all dependencies
        cmds:
            - pnpm install
            - task: core:install
            - task: client:install
            - task: interface:install
            - task: server:install

    dev:
        deps: [interface:dev, client:dev]
